### ISSUE TITLE
Debugging session not stopping on breakpoints

### ISSUE THREAD

**Issue by benoitcerrina** [provegard/ncdbg#100]
Hello,
recently (maybe a week or two ago) ncdbg stopped working correctly for me.
In particular breakpoints don't work.
I am using chrome version 69.0.3497.100

**Comment by benoitcerrina** [comment]
[ncdbg.log](https://github.com/provegard/ncdbg/files/2464862/ncdbg.log)
Attached is a log of the issue happening

**Comment by provegard** [comment]
Sorry for the delay! I will take a look tomorrow.

**Comment by provegard** [comment]
I'm unable to reproduce. I have one small discrepancy compared to your log output though - which OS are you using?

**Comment by provegard** [comment]
Interestingly:

```
xplan/xP lanDataAnalytics
https://
```

The stripped part is equal in length to "https://". Perhaps a coincidence though.

**Comment by benoitcerrina** [comment]
Hello I am using windows 10
I think I am using the latest master unless I made a mistake using git so I will recheck

**Comment by provegard** [comment]
Do you load scripts using the `load` extension?

**Comment by provegard** [comment]
Also, what does the source tree in DevTools look like? Can you post a screenshot that shows the script in question?

**Comment by provegard** [comment]
Ok, I can reproduce by adding a sourceURL comment to my test script. Does your script contain sourceURL?

**Comment by provegard** [comment]
I found the following fix in DevTools:

https://github.com/ChromeDevTools/devtools-frontend/commit/6fc46fbf18af8001200fb9f60a55c2645eaaddf1

That fix is not in Chrome 69.0.3497.100, however.

I'm a bit reluctant to create a workaround if the fix above gets into Chrome soon anyway.

Can you remove sourceURL (if you have it) in the meantime?

**Comment by provegard** [comment]
That's odd - sourceURL was the only way for me to reproduce. Perhaps the correct way is to prefix all URLs with file:///.

You can try removing the v8only query string parameter from the DevTools URL. It may have side effects though.

**Comment by benoitcerrina** [comment]
hello removing the v8only query string worked in my first test.  I will confirm to you tomorrow if it worked completely.  
Thanks for your support

**Comment by Deepashreehg** [comment]
Hello, the fix works for me in all scenarios. 
Thank you.

**Comment by benoitcerrina** [comment]
hello did knowing that removing the v8only parameter help understand what is going on.  Still unsure why see the problem and you don't and what could be the difference between our configurations

**Comment by provegard** [comment]
The v8only parameter enables some NodeJS logic inside the DevTools frontend, among other things the stripping of `file:///` which in your case is problematic since the URL doesn't start with that prefix. Not sure why I'm not seeing the same thing unless I add `sourceURL` to the script.

But I'll do some tests without v8only and if everything seems to work (as @Deepashreehg suggests) then I'll update the log message that shows the DevTools link to open in Chrome.

**Comment by brainopener** [comment]
@provegard We had the same problem with scripting in Jira ([we're working over here](https://github.com/BigBrassBand/jira-git-workflow-hooks)) and removing the v8only parameter fixed us up.

**Comment by provegard** [comment]
@brainopener thanks for letting me know! I will make a release where I remove the `v8only` parameter (and possibly `experimental` as well) from the link that is shown in the log. I've had some busy weeks though, so I haven't managed to find time for it.
