### ISSUE TITLE
not stopping on breakpoint  #100 is back

### ISSUE THREAD

**Issue by benoitcerrina** [provegard/ncdbg#102]
Hello,
I have had to use the debugger for the first time in a while and I noticed that the v8only parameter is not in the url provided.  However I am experiencing similar issue as mentioned in issue #100, my breakpoints are not working and I can see in the traces 
(in the case where I used sourceURL)
Setting an unresolved breakpoint with ID ndb4 at line 180 in script with URL xplan/repairCanBeReadBy       
(in the case without sourceURL)
Setting an unresolved breakpoint with ID ndb1 at line 180 in script with URL eval:///Script23

**Comment by benoitcerrina** [comment]
closing, my colleague doesn't see the problem, I need more investigation on our side

**Comment by provegard** [comment]
Ok! Let me know if you find anything.
