### ISSUE TITLE
Getting error when performing property extraction

### ISSUE THREAD

**Issue by JayBerlin** [provegard/ncdbg#68]
I am running the latest version of NCDbg and I am getting the following error on the Chrome console when trying to get Object property values:

Error: 'Error from object property extraction: jdk.nashorn.internal.runtime.ECMAException: SyntaxError: <eval>:8:40 Expected { but found blacklistRegExp
      var includeProp = function (prop) blacklistRegExp ? !prop.match(blacklistRegExp) : true
                                        ^
	at data (ui://lz.ui-330d03986d154714bf108bef399b4357/components/lz_csi_list_filter/LzCSIListFilterServer.js:18)
	at ajax_getFilters (ui://lz.ui-330d03986d154714bf108bef399b4357/components/lz_csi_list_filter/LzCSIListFilterServer.js:34)' for object '{"id":"$$locals-ndsf1"}'

This is coming from PropertyHolder.scala:153:

      var includeProp = function (prop) (blacklistRegExp ? !prop.match(blacklistRegExp) : true)

If I change the above line to the following, things work properly and I can see all of my Local variable again:

      var includeProp = function (prop) { return (blacklistRegExp ? !prop.match(blacklistRegExp) : true) }

**Comment by provegard** [comment]
Good catch, that syntax is a Nashorn extension. I assume you have those turned off?

**Comment by JayBerlin** [comment]
We do.  There are reasons that we do not allow the extensions at this time.

**Comment by provegard** [comment]
Sure, no problem. I'll have a fix up in a few minutes.

**Comment by provegard** [comment]
Fixed. Let me know if you run into anything else! Thanks for reporting! :-)

**Comment by JayBerlin** [comment]
Thanks!  Really like this project.  It is exactly what we were looking for.  Will report anything else we run into, but so far, things have been working!

**Comment by provegard** [comment]
Thanks, good to hear! :-)
