### ISSUE TITLE
can't step into

### ISSUE THREAD

**Issue by benoitcerrina** [provegard/ncdbg#95]
recently I have not been able to step into most methods.
I have the following message in the log:
Failed to handle message: Cannot create domain method Debugger.stepInto because there are arguments
I am fairly sure this used to work

**Comment by provegard** [comment]
I'll take a look!

**Comment by provegard** [comment]
Fixed, could you please test?

**Comment by benoitcerrina** [comment]
still saw it this morning.  I will check again, I may have messed up the refresh

**Comment by benoitcerrina** [comment]
Getting some proxy error when trying to fetch, our IT must have changed something. I'll keep you updated once I have managed to test the latest version

**Comment by benoitcerrina** [comment]
OK fixed the proxy issue on my side and tested.  I confirmed that I am not reproducing anymore.  Thanks for closing it.

**Comment by provegard** [comment]
Good to hear, thanks for reporting!
