### ISSUE TITLE
Keep Application Running

### ISSUE THREAD

**Issue by augustocdias** [provegard/ncdbg#96]
It would be nice to have the application running through multiple debug sessions, so we don't have to start it everytime we want to debug an app. Having the app running as a service would improve the overall debugging experience.

**Comment by provegard** [comment]
I got the suggestion elsewhere to let NCDbg connect first when DevTools connects. That requires a separation of lifecycles anyway and I think it would align with what you suggest. Do you agree?

**Comment by provegard** [comment]
I have pushed something that I think addresses this issue. If you start NCDbg with the `--lazy` option, it won't connect until you connect with DevTools, and it will stay alive if the debug target dies.

I haven't made a release with this functionality yet, but you can try it directly from the repo. Let me know if it works for you!

**Comment by augustocdias** [comment]
Worked like a charm. Thank you very much
